LOCATIONS = {
    'Maputo Cidade': {
        'KaMpfumo': ['KaMpfumo'],
        'Nlhamankulu': ['Nlhamankulu'],
        'KaMaxakeni': ['KaMaxakeni'],
        'KaMavota': ['KaMavota'],
        'KaMubukwana': ['KaMubukwana'],
        'KaTembe': ['KaTembe'],
        'KaNyaka': ['KaNyaka'],
    },
    'Maputo Província': {
        'Boane': ['Boane', 'Matola-Rio'],
        'Magude': ['Magude', 'Mapulanguene', 'Mahele', 'Motaze', 'Phadjane'],
        'Manhiça': ['Manhiça', 'Xinavane', '3 de Fevereiro', 'Calanga', 'Ilha Josina Machel', 'Maluana'],
        'Marracuene': ['Marracuene', 'Machubo'],
        'Matutuíne': ['Zitundo', 'Bela Vista', 'Catembe', 'Catuane', 'Machangulo'],
        'Moamba': ['Moamba', 'Ressano Garcia', 'Pessene', 'Sabie'],
        'Namaacha': ['Namaacha', 'Changalane'],
        'Matola': ['Matola', 'Machava']
    },
    'Gaza': {
        'Bilene': ['Macia', 'Praia do Bilene', 'Mazivila', 'Messano'],
        'Chibuto': ['Chibuto', 'Chaimite', 'Godide', 'Malehice'],
        'Chicualacuala': ['Mapai', 'Eduardo Mondlane', 'Pafuri'],
        'Chigubo': ['Chigubo', 'Dindiza', 'Zinhane'],
        'Chókwè': ['Chókwè', 'Lionde', 'Macarretane', 'Xilembene'],
        'Guijá': ['Caniçado', 'Chivongoene', 'Mubangoene', 'Nalazi'],
        'Mabalane': ['Mabalane', 'Combomune', 'Ntlavene'],
        'Manjacaze': ['Manjacaze', 'Chidenguele', 'Chibonzane', 'Macuacua', 'Mazimechopes', 'Mandlakazi'],
        'Massangena': ['Massangena', 'Mavue', 'Nwana-Neto'],
        'Massingir': ['Massingir', 'Zulo', 'Mavodze'],
        'Xai-Xai': ['Xai-Xai', 'Chongoene', 'Chicumbane'],
    },
    'Inhambane': {
        'Funhalouro': ['Funhalouro', 'Tome'],
        'Govuro': ['Nova Mambone', 'Save'],
        'Homoine': ['Homoine', 'Pembe'],
        'Inharrime': ['Inharrime', 'Mucumbi'],
        'Inhassoro': ['Inhassoro', 'Bazaruto'],
        'Jangamo': ['Jangamo', 'Cumbana'],
        'Mabote': ['Mabote', 'Zimane', 'Zinave'],
        'Massinga': ['Massinga', 'Chicomo'],
        'Maxixe': ['Maxixe', 'Bembe'],
        'Morrumbene': ['Morrumbene', 'Mocodoene'],
        'Panda': ['Panda', 'Mawayela'],
        'Vilankulo': ['Vilankulo', 'Mapi-ne'],
        'Zavala': ['Zavala', 'Quissico'],
    },
    'Sofala': {
        'Beira': ['Beira'],
        'Buzi': ['Buzi', 'Estaquinha', 'Nova Sofala'],
        'Caia': ['Caia', 'Sena', 'Murraça'],
        'Chemba': ['Chemba', 'Chirinje'],
        'Cheringoma': ['Inhaminga', 'Dondo'],
        'Chibabava': ['Chibabava', 'Goonda'],
        'Dondo': ['Dondo', 'Mafambisse'],
        'Gorongosa': ['Gorongosa', 'Vanduzi'],
        'Machanga': ['Machanga', 'Chiloane'],
        'Marromeu': ['Marromeu', 'Chupanga'],
        'Muanza': ['Muanza', 'Galinha'],
        'Nhamatanda': ['Nhamatanda', 'Tica'],
    },
    'Manica': {
        'Bárue': ['Catandica', 'Choa', 'Nhampassa'],
        'Gondola': ['Gondola', 'Amatongas', 'Inchope'],
        'Guro': ['Guro', 'Mungari', 'Dacata'],
        'Machaze': ['Machaze', 'Save'],
        'Macossa': ['Macossa', 'Nguawala'],
        'Manica': ['Manica', 'Messica', 'Mavonde'],
        'Mossurize': ['Espungabera', 'Dacata'],
        'Sussundenga': ['Sussundenga', 'Dombe', 'Muhoa'],
        'Tambara': ['Tambara', 'Nhacolo'],
        'Chimoio': ['Chimoio']
    },
    'Tete': {
        'Angónia': ['Ulongué', 'Domué'],
        'Cahora-Bassa': ['Songo', 'Chitima'],
        'Changara': ['Luenha', 'Chioco'],
        'Chifunde': ['Chifunde', 'Mualadzi'],
        'Chiuta': ['Manje', 'Kazula'],
        'Macanga': ['Furancungo', 'Chirara'],
        'Magoé': ['Magoé', 'Chinthopo'],
        'Marara': ['Marara', 'Katchembe'],
        'Marávia': ['Fingoe', 'Chiputo'],
        'Moatize': ['Moatize', 'Zobue'],
        'Mutarara': ['Nhamayabué', 'Inhangoma'],
        'Tsangano': ['Tsangano', 'Ntengo-wambalame'],
        'Tete': ['Tete'],
        'Zumbo': ['Zumbo', 'Muze'],
    },
    'Zambézia': {
        'Alto Molócuè': ['Alto Molócuè', 'Nivava'],
        'Chinde': ['Chinde', 'Luabo'],
        'Derre': ['Derre', 'Machado'],
        'Gilé': ['Gilé', 'Alto Ligonha'],
        'Gurué': ['Gurué', 'Lioma'],
        'Ile': ['Ile', 'Socone'],
        'Inhassunge': ['Inhassunge', 'Mucupia'],
        'Lugela': ['Lugela', 'Tacuane'],
        'Maganja da Costa': ['Maganja da Costa', 'Nante'],
        'Milange': ['Milange', 'Molumbo'],
        'Mocuba': ['Mocuba', 'Mugeba'],
        'Mopeia': ['Mopeia', 'Campo'],
        'Morrumbala': ['Morrumbala', 'Chire'],
        'Namacurra': ['Namacurra', 'Macuse'],
        'Namarroi': ['Namarroi', 'Regone'],
        'Nicoadala': ['Nicoadala', 'Maquival'],
        'Pebane': ['Pebane', 'Mulela'],
        'Quelimane': ['Quelimane'],
    },
    'Nampula': {
        'Angoche': ['Angoche', 'Aube', 'Boila-Nametoria', 'Namaponda'],
        'Eráti': ['Namapa-Eráti', 'Alua', 'Namiroa'],
        'Ilha de Moçambique': ['Ilha de Moçambique', 'Lumbo'],
        'Lalaua': ['Lalaua', 'Meti'],
        'Malema': ['Malema', 'Chihulo', 'Mutuali'],
        'Meconta': ['Meconta', 'Corrane', 'Namialo', '7 de Abril'],
        'Mecubúri': ['Mecubúri', 'Milhana', 'Muite', 'Namina'],
        'Memba': ['Memba', 'Chipene', 'Lurio', 'Mazua'],
        'Mogincual': ['Mogincual', 'Quinga', 'Chunga', 'Naminge'],
        'Mogovolas': ['Nametil', 'Calipo', 'Ilute', 'Muatua', 'Nanhupo'],
        'Moma': ['Moma', 'Macone', 'Larde', 'Mucuali'],
        'Monapo': ['Monapo', 'Itoculo', 'Netia'],
        'Mossuril': ['Mossuril', 'Lunga', 'Matibane'],
        'Muecate': ['Muecate', 'Imala', 'Muculuone'],
        'Murrupula': ['Murrupula', 'Chinga', 'Nehessine'],
        'Nacala-a-Velha': ['Nacala-a-Velha', 'Covo'],
        'Nacala Porto': ['Nacala Porto'],
        'Nacarôa': ['Nacarôa', 'Intete', 'Saua-Saua'],
        'Nampula': ['Nampula'],
        'Rapale': ['Rapale', 'Anchilo'],
        'Ribaué': ['Ribaué', 'Iapala', 'Kunle'],
        'Larde': ['Larde'],
        'Liupo': ['Liupo']
    },
    'Cabo Delgado': {
        'Ancuabe': ['Ancuabe', 'Metoro', 'Meza'],
        'Balama': ['Balama', 'Impiri', 'Kwekwe', 'Mavala'],
        'Chiúre': ['Chiúre', 'Katapua', 'Mazeze', 'Namogelia', 'Ocua'],
        'Ibo': ['Ibo', 'Quirimba'],
        'Macomia': ['Macomia', 'Chai', 'Mucojo', 'Quiterajo'],
        'Mecúfi': ['Mecúfi', 'Murrebue'],
        'Meluco': ['Meluco', 'Muaguide'],
        'Mocímboa da Praia': ['Mocímboa da Praia', 'Diaca', 'Mbau'],
        'Montepuez': ['Montepuez', 'Mapupulo', 'Mirate', 'Nairoto', 'Namanhumbir'],
        'Mueda': ['Mueda', 'Chapa', 'Imbuho', 'Negomano', "N'gapa"],
        'Muidumbe': ['Muidumbe', 'Chitunda', 'Miteda'],
        'Namuno': ['Namuno', 'Hucula', 'Machoca', 'Meloco', 'Ncumpe', 'Papá'],
        'Nangade': ['Nangade', 'Ntamba'],
        'Palma': ['Palma', 'Olumbi', 'Pundanhar', 'Quionga'],
        'Pemba': ['Pemba'],
        'Quissanga': ['Quissanga', 'Bilibiza', 'Mahate'],
    },
    'Niassa': {
        'Cuamba': ['Cuamba', 'Etatara', 'Lúrio'],
        'Lago': ['Metangula', 'Cobue', 'Lunho', 'Maniamba'],
        'Lichinga': ['Lichinga', 'Lione', 'Meponda'],
        'Majune': ['Majune', 'Malanga', 'Nairrubi'],
        'Mandimba': ['Mandimba', 'Lissiete', 'Mitande'],
        'Marrupa': ['Marrupa', 'Nungo'],
        'Maúa': ['Maúa', 'Maiaca'],
        'Mavago': ['Mavago', "M'sawisze"],
        'Mecanhelas': ['Mecanhelas', 'Chiuta', 'Insaca'],
        'Mecula': ['Mecula', 'Matondovela'],
        'Metarica': ['Metarica', 'Mucunha', 'Namacunde'],
        'Muembe': ['Muembe', 'Chiconono'],
        "N'gauma": ["N'gauma", 'Itepela', 'Massangulo'],
        'Namarroi': ['Namarroi', 'Regone'],
        'Nipepe': ['Nipepe', 'Muipaze'],
        'Sanga': ['Sanga', 'Lussimbesse', 'Macaloge', 'Matchedje'],
    }
}

def get_provinces():
    """Retorna uma lista de todas as províncias."""
    return list(LOCATIONS.keys())

def get_districts(province):
    """Retorna uma lista de distritos para uma determinada província."""
    if province in LOCATIONS:
        return list(LOCATIONS[province].keys())
    return []

def get_admin_posts(province, district):
    """Retorna uma lista de postos administrativos para uma determinada província e distrito."""
    if province in LOCATIONS and district in LOCATIONS[province]:
        return LOCATIONS[province][district]
    return []
